In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/Users/eldanizarifzada/Downloads/heart_cleveland_upload.csv')

In [3]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0


In [6]:
X=df.drop('condition', axis=1)
y=df['condition']

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.1)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
def printMetrics(y_pred, y_actual):
    print('Accuracy is ' + str(accuracy_score(y_pred, y_actual)))
    print('Confusion Matrix')
    print(confusion_matrix(y_pred, y_actual))
    print('Classification report')
    print(classification_report(y_pred, y_actual))

In [17]:
dt=DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred_dt=dt.predict(X_test)

printMetrics(pred_dt, y_test)

Accuracy is 0.5666666666666667
Confusion Matrix
[[12  9]
 [ 4  5]]
Classification report
              precision    recall  f1-score   support

           0       0.75      0.57      0.65        21
           1       0.36      0.56      0.43         9

    accuracy                           0.57        30
   macro avg       0.55      0.56      0.54        30
weighted avg       0.63      0.57      0.58        30



In [19]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)
pred_rf=rf.predict(X_test)

printMetrics(pred_rf, y_test)

Accuracy is 0.8
Confusion Matrix
[[14  4]
 [ 2 10]]
Classification report
              precision    recall  f1-score   support

           0       0.88      0.78      0.82        18
           1       0.71      0.83      0.77        12

    accuracy                           0.80        30
   macro avg       0.79      0.81      0.80        30
weighted avg       0.81      0.80      0.80        30



In [21]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [23]:
param_grid = {
    'criterion' : ['gini', 'entropy'],
    'max_depth': [None, 2, 4, 6, 8, 10, 15, 5, 7],
    'min_samples_split' : [2, 5, 10, 3, 4, 7],
    'min_samples_leaf' : [1, 2, 4, 3, 10, 15]
}

dt=DecisionTreeClassifier()
grid_search=GridSearchCV(estimator=dt, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=3)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 648 candidates, totalling 3240 fits
[CV 1/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2;, score=0.796 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=10;, score=0.833 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=10;, score=0.741 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=10;, score=0.717 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=10;, score=0.887 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=10;, score=0.717 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=3;, score=0.796 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=4;, score=0.796 total 

/opt/anaconda3/lib/python3.12/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2, 4, 6, 8, 10, 15, 5, 7],
                         'min_samples_leaf': [1, 2, 4, 3, 10, 15],
                         'min_samples_split': [2, 5, 10, 3, 4, 7]},
             scoring='accuracy', verbose=3)

In [24]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 8,
 'min_samples_leaf': 1,
 'min_samples_split': 7}

In [25]:
grid_search.best_score_

0.8089447938504544

In [29]:
new_model= DecisionTreeClassifier(**grid_search.best_params_)
new_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=8, min_samples_split=7)

In [31]:
grid_prediction= grid_search.predict(X_test)

printMetrics(grid_prediction, y_test)

Accuracy is 0.6
Confusion Matrix
[[12  8]
 [ 4  6]]
Classification report
              precision    recall  f1-score   support

           0       0.75      0.60      0.67        20
           1       0.43      0.60      0.50        10

    accuracy                           0.60        30
   macro avg       0.59      0.60      0.58        30
weighted avg       0.64      0.60      0.61        30



In [35]:
#grid_search.cv_results_

In [37]:
random_search= RandomizedSearchCV(estimator=dt, param_distributions=param_grid, n_iter=10, cv=5, scoring='accuracy', random_state=42, n_jobs=-1)

In [39]:
random_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [None, 2, 4, 6, 8, 10, 15,
                                                      5, 7],
                                        'min_samples_leaf': [1, 2, 4, 3, 10,
                                                             15],
                                        'min_samples_split': [2, 5, 10, 3, 4,
                                                              7]},
                   random_state=42, scoring='accuracy')

In [41]:
random_search.best_params_

{'min_samples_split': 3,
 'min_samples_leaf': 15,
 'max_depth': 4,
 'criterion': 'entropy'}

In [43]:
random_search.best_score_

0.7977638015373865

In [45]:
new_model2 = DecisionTreeClassifier(**random_search.best_params_)

In [47]:
random_pred=random_search.predict(X_test)

printMetrics(random_pred, y_test)

Accuracy is 0.7
Confusion Matrix
[[13  6]
 [ 3  8]]
Classification report
              precision    recall  f1-score   support

           0       0.81      0.68      0.74        19
           1       0.57      0.73      0.64        11

    accuracy                           0.70        30
   macro avg       0.69      0.71      0.69        30
weighted avg       0.72      0.70      0.71        30



In [49]:
printMetrics(grid_prediction, y_test)

Accuracy is 0.6
Confusion Matrix
[[12  8]
 [ 4  6]]
Classification report
              precision    recall  f1-score   support

           0       0.75      0.60      0.67        20
           1       0.43      0.60      0.50        10

    accuracy                           0.60        30
   macro avg       0.59      0.60      0.58        30
weighted avg       0.64      0.60      0.61        30



In [52]:
param_grid = {
    'n_estimators': [50, 100, 150, 200, 30, 40, 70, 90],
    'max_depth' : [None, 5, 10, 15, 20, 25],
    'min_samples_split' : [2, 4, 5, 15, 20, 10],
    'min_samples_leaf' : [1,2,3,5,6,7,8],
    'criterion' : ['gini', 'entropy']
}

rf2=RandomForestClassifier()

grid_search_rf=GridSearchCV(estimator=rf2, param_grid=param_grid, cv=5, scoring='f1', n_jobs=-1)

grid_search_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 15, 20, 25],
                         'min_samples_leaf': [1, 2, 3, 5, 6, 7, 8],
                         'min_samples_split': [2, 4, 5, 15, 20, 10],
                         'n_estimators': [50, 100, 150, 200, 30, 40, 70, 90]},
             scoring='f1')

In [54]:
random_search= RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=60,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2,
    random_state=42
)

random_search.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=5, n_estimators=70; total time=   0.1s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=5, n_estimators=70; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=5, n_estimators=90; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=15, n_estimators=40; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=15, n_estimators=40; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=15, n_estimators=70; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=15, n_estimators=70; total time=   0.0s
[CV] END criterion=entropy, max_depth=25, min_samples_leaf=1, min_samples_split=20, n_estimators=150

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=60,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [None, 5, 10, 15, 20, 25],
                                        'min_samples_leaf': [1, 2, 3, 5, 6, 7,
                                                             8],
                                        'min_samples_split': [2, 4, 5, 15, 20,
                                                              10],
                                        'n_estimators': [50, 100, 150, 200, 30,
                                                         40, 70, 90]},
                   random_state=42, scoring='accuracy', verbose=2)

In [56]:
random_search.best_params_

{'n_estimators': 90,
 'min_samples_split': 20,
 'min_samples_leaf': 8,
 'max_depth': 25,
 'criterion': 'entropy'}

In [58]:
random_forest_random_pred=random_search.predict(X_test)

In [60]:
printMetrics(random_forest_random_pred, y_test)

Accuracy is 0.8333333333333334
Confusion Matrix
[[16  5]
 [ 0  9]]
Classification report
              precision    recall  f1-score   support

           0       1.00      0.76      0.86        21
           1       0.64      1.00      0.78         9

    accuracy                           0.83        30
   macro avg       0.82      0.88      0.82        30
weighted avg       0.89      0.83      0.84        30



In [62]:
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [64]:
gb_model=GradientBoostingClassifier()
xgb_model=XGBClassifier()

param_grid={
    'n_estimators' : [50, 75, 100],
    'learning_rate' : [0.01, 0.2, 0.3],
    'max_depth': [3,5],
    'subsample': [0.8, 1.0]
}

randomized_search_gb=RandomizedSearchCV(estimator=gb_model, param_distributions=param_grid,cv=5, scoring='accuracy', n_jobs=-1, verbose=2)

In [66]:
randomized_search_gb.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=GradientBoostingClassifier(), n_jobs=-1,
                   param_distributions={'learning_rate': [0.01, 0.2, 0.3],
                                        'max_depth': [3, 5],
                                        'n_estimators': [50, 75, 100],
                                        'subsample': [0.8, 1.0]},
                   scoring='accuracy', verbose=2)

In [68]:
randomized_search_gb.best_params_

{'subsample': 1.0, 'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.01}

In [70]:
randomized_search_gb.best_score_

0.8054507337526206

In [72]:
printMetrics(randomized_search_gb.predict(X_test), y_test)

Accuracy is 0.8
Confusion Matrix
[[15  5]
 [ 1  9]]
Classification report
              precision    recall  f1-score   support

           0       0.94      0.75      0.83        20
           1       0.64      0.90      0.75        10

    accuracy                           0.80        30
   macro avg       0.79      0.82      0.79        30
weighted avg       0.84      0.80      0.81        30



In [84]:
xgb=XGBClassifier(eval_metric='mlogloss',random_state=42)

param_grid={
    'n_estimators' : [50, 75, 100],
    'learning_rate' : [0.01, 0.2, 0.3],
    'max_depth': [3,5],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

grid_search_xgb=GridSearchCV(estimator=xgb, param_grid=param_grid,cv=5, scoring='accuracy', n_jobs=-1, verbose=2)

grid_search_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False,
                                     eval_metric='mlogloss', feature_types=None,
                                     feature_weights=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constrain...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.8, 1.0],
                         'learning_rate': [0.01, 0.2, 0.3], 'max_depth': [3, 5],
                         'n_estimators': [50, 75, 100],
                         'subsample': [0.8, 1.0]},
             scoring='accuracy', verbose=2)

In [98]:
y_pred=grid_search_xgb.predict(X_test)
printMetrics(y_pred, y_test)

Accuracy is 0.8333333333333334
Confusion Matrix
[[16  5]
 [ 0  9]]
Classification report
              precision    recall  f1-score   support

           0       1.00      0.76      0.86        21
           1       0.64      1.00      0.78         9

    accuracy                           0.83        30
   macro avg       0.82      0.88      0.82        30
weighted avg       0.89      0.83      0.84        30



In [76]:
grid_search_xgb.best_params_

{'colsample_bytree': 0.8,
 'learning_rate': 0.01,
 'max_depth': 5,
 'n_estimators': 50,
 'subsample': 0.8}

In [78]:
grid_search_xgb.best_score_

0.823969252271139